= CRS Service

image:https://github.com/pdssp/crs-service/actions/workflows/build.yaml/badge.svg?branch=main["Build Status", link="https://github.com/pdssp/crs-service/actions/workflows/build.yaml?query=branch%3Amain"]
image:https://img.shields.io/badge/Powered_by-Apache_SIS-blue[Powered by Apache SIS, link='https://github.com/apache/sis']
image:https://img.shields.io/badge/Powered_by-Spring_Boot-green[Powered by Spring Boot, link='https://github.com/spring-projects/spring-boot']

A web-service that provides code snippets for coordinate conversions.

link:src/docs/asciidoc/features.adoc[_Learn more about its features and limitations_].

== Requirements

* JDK 21
* *Optional* Gradle 8.10.2 if you rather use `gradle` command instead of the `./gradlew` wrapper command (that downloads Gradle for you)

== Usage

The following command compiles and launch the webservice locally on port 8080:

[source,shell]
----
./gradlew bootRun
----

To start on another port, do:

[source,shell]
----
./gradlew bootRun --args="--server.port=8081"
----

To use IAU definitions directly from Planetary CRS registry Github repository, use the following command:

[source,shell]
----
./gradlew bootRun --args="--geomatys.iau.factory.wkt.file=https://raw.githubusercontent.com/pdssp/planet_crs_registry/refs/heads/main/data/result.wkts"
----

To compile the project without launching the service:

[source,shell]
----
./gradlew build
----

== Documentation

Project technical documentation is available link:./src/docs/asciidoc/index.adoc[here].

== Contribute

=== CRS Operation REST API

The service offers a `/crs/operation` GET and POST endpoint to query a CRS Operation source code.

GET example: http://localhost:8080/crs/operation?source=CRS:84&target=EPSG:4326&format=text/javascript

The service responsible for this operation is link:src/main/java/com/geomatys/crsservice/service/CrsOperationService.java[CRSOperationService interface]. To customize behavior, replace or modify the only implementation of this interface.

=== Integration tests

To make tests that simulate the web service, inherit the `AbstractIntegrationTest` class.
It provides a web client (through `createClient()` method) that you can use to simulate HTTP requests to the server.
