== Deployment

=== Kubernetes

To deploy on Kubernetes, Helm can be used:

[source,shell]
----
helm repo add geomatys.public https://nexus.geomaty.com/repository/helm-public
helm upgrade --install --atomic --debug \
     --kube-context=my-kube-cluster -n my-namespace \
      --set="image.repository=pdssp/crs-service"
      --values my-values.yaml
      my-release-name geomatys.public/spring-boot-web
----

Below is an example value file that can be completed to your needs:

[source,yaml]
----
ingress:
  enabled: true
  hosts:
    - demo.geomatys.com # <.>

config:
  server:
    servlet:
      context-path: "/crs-service" # <.>

resources:
  requests: # <.>
    cpu: "0.2"
    memory: 1024Mi
  limits: # <.>
    cpu: "1"
    memory: 2048Mi

env:
  JAVA_TOOL_OPTIONS: "-Xms512M -Xmx1536M" <.>
----
<.> Hostname the application is deployed on
<.> Prefix URL to use to reach application (define both Spring application context path and Ingress prefix path)
<.> Minimal CPU and memory requirements for deployment
<.> Maximal usable CPU and memory amount
<.> Configure JVM "heap size" accordingly to resource specifications above (should be lower than memory limit)

Using above configuration, application would be deployed on http://demo.geomatys.com/crs-service[].

Using this deployment method, the `config` section from the values file is mounted as an external `application.yaml` file (see https://docs.spring.io/spring-boot/reference/features/external-config.html[Spring Boot externalized configuration] for more details).

=== Docker or Docker-compose

The web service docker image is published on `pdssp/crs-service:latest` repository.

*Compose* configuration example:

[source,yaml]
.compose.yaml
----
name: crs-service

services:
  crs-service:
    image: images.geomatys.com/projects/cnes/crs-service:latest
    ports:
      - 8080:8080
    environment:
      # JVM environment variables. Here, configure Java Heap space
      JAVA_TOOL_OPTIONS: -Xms512M -Xmx1024M
      # File to read to load IAU CRS definitions. If not set, a default embedded definition file will be used.
      GEOMATYS_IAU_FACTORY_WKT_FILE: https://raw.githubusercontent.com/pdssp/planet_crs_registry/refs/heads/main/data/result.wkts
      # Text encoding of the WKT file
      GEOMATYS_IAU_FACTORY_WKT_CHARSET: UTF-8
----


=== About configuration options

[NOTE]
====
Application configuration uses https://docs.spring.io/spring-boot/reference/features/external-config.html[Spring Boot externalized configuration].
In this documentation, a property called `my.own-property` can therefore be set either:

* as an environment variable `MY_OWNPROPERTY`
* as command-line argument `--my.own-property`
====

==== Planetary system definitions: IAU authority

Properties controlling IAU CRS definition loading are:

* `geomatys.iau.factory.wkt.file`: Local path or Http URL to the text file providing all WKT definitions that must be loaded under IAU authority (defaults to https://github.com/pdssp/crs-service/tree/main/src/main/resources/static/IAU.txt[embedded definition file])
* `geomatys.iau.factory.wkt.charset`: Text encoding to use when reading definition file (`UTF-8` by default)
